include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/libtarp_cmake_utils.cmake)

get_os_info( OS_ID OS_VERSION_ID OS_NAME_ID )

SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "1")

set(CPACK_GENERATOR "DEB;RPM;TGZ")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "dcris")
SET(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

SET(CPACK_PACKAGE_FILE_NAME ${CMAKE_PROJECT_NAME}-${OS_ID}.${OS_VERSION_ID}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH})
message( STATUS "CPACK_PACKAGE_FILE_NAME is ${CPACK_PACKAGE_FILE_NAME}" )
message( STATUS "CPACK_PACKAGING_INSTALL_PREFIX is ${CPACK_PACKAGING_INSTALL_PREFIX}")

SET(CPACK_DEBIAN_PACKAGE_DEPENDS "python3" )

string(COMPARE EQUAL ${OS_NAME_ID} "ubuntu-16.04" ARE_SAME )

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
	"${CMAKE_CURRENT_SOURCE_DIR}/package/preinst;${CMAKE_CURRENT_SOURCE_DIR}/package/postinst;${CMAKE_CURRENT_SOURCE_DIR}/package/prerm;${CMAKE_CURRENT_SOURCE_DIR}/package/postrm")

include(CPack)
